[package]
name = "http-plz"
version = "0.0.12"
authors = ["darkseid", "sytten <emile@caido.io>"]
description = "HTTP structs used by the ParsePlz organisation"
repository = "https://github.com/parseplz/http-plz"
license = "MIT"
edition = "2024"

[dependencies]
body-plz = "0.0.55"
bytes = "1.11.1"
decompression-plz = "0.0.32"
header-plz = "0.0.50"
thiserror = "2.0.18"
bon = "3.9.1"

[dev-dependencies]
rstest = "0.26.1"

[lints.clippy]
unwrap_used = "deny"
