[package]
name = "http-plz"
version = "0.0.3"
authors = ["darkseid", "sytten <emile@caido.io>"]
description = "HTTP structs used by the ParsePlz organisation"
repository = "https://github.com/parseplz/http-plz"
license = "MIT"
edition = "2024"

[dependencies]
body-plz = "0.0.48"
bytes = "1.11.1"
decompression-plz = "0.0.25"
header-plz = "0.0.44"
thiserror = "2.0.18"

[lints.clippy]
unwrap_used = "deny"
